# Generated by Django 4.0.5 on 2022-09-27 13:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=32)),
                ('cidade', models.CharField(max_length=100)),
                ('tipo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=400)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=16)),
                ('anoinauguracao', models.IntegerField(validators=[django.core.validators.MinValueValidator(-9999), django.core.validators.MaxValueValidator(3000)])),
                ('funcionamento', models.CharField(max_length=100)),
                ('curiosidades', models.TextField(null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=32)),
                ('comentario', models.CharField(max_length=32)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 10, 17, 14, 931883))),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC.patrimonio')),
            ],
        ),
    ]
