# Generated by Django 4.0.5 on 2022-10-21 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 20, 9, 13, 667983)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('S', 'Auxiliar'), ('A', 'Administrador')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC.cidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PC.cidade'),
        ),
    ]
