# Generated by Django 4.0.5 on 2022-11-03 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0002_cidade_alter_comentario_data_alter_usuario_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 21, 56, 45, 51693)),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='foto',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
